name: Lint

on: [ push, pull_request ]

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: test/ci/run-codespell.sh

  jing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo npm install -g bats
      - run: >
          source test/ci/install-jing.sh
          && bats --tap test/rnc.bats

  shfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo snap install shfmt
      - run: shfmt -d .
